name: Minisign test

on:
  push:

  workflow_dispatch:

jobs:
  minisign-test:
    runs-on: ubuntu-latest

    steps:

      - name: Set VyOS version
        id: set_vyos_version
        run: |
          echo "VYOS_VERSION=1.4-rolling-$(date -u +%Y%m%d%H%M)" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Update latest_build.txt
        run: echo $(date -u +%Y%m%d%H%M) > $GITHUB_WORKSPACE/latest_build.txt

      - name: Create autocommit and tag
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          tagging_message: ${{ env.VYOS_VERSION }}
          commit_message: ${{ env.VYOS_VERSION }}

      - run: |
          echo $VYOS_VERSION > vyos-$VYOS_VERSION-amd64.iso

      - name: Publish release
        uses: softprops/action-gh-release@v1
        id: release
        with:
          tag_name: ${{ env.VYOS_VERSION }}
          fail_on_unmatched_files: true
          files: |
            ./vyos-${{ env.VYOS_VERSION }}-amd64.iso

      - name: Print Variable
        run: |
          echo "Value of release_urls: $release_urls"
        env:
          release_urls: ${{ fromJSON(steps.release.outputs.assets)[0].browser_download_url }}
