name: Minisign test

on:
  push:

  workflow_dispatch:

env:
  minisign_key: ${{ secrets.minisign_key }}
  minisign_password: ${{ secrets.minisign_password }}

jobs:
  minisign-test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - run: |
          echo TEST > test.txt
          echo 'untrusted comment: minisign encrypted secret key' > minisign.key
          echo $minisign_key >> minisign.key
          shasum minisign.key
          echo $minisign_password | $GITHUB_WORKSPACE/bin/minisign -s minisign.key -Sm test.txt 

      - uses: actions/upload-artifact@v3
        with:
          name: test.txt.minisig
          path: test.txt.minisig