name: Fail test workflow

on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:

      - name: Send Slack notification on fail
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Repository: ${GITHUB_REPOSITORY}\\nWorkflow: ${GITHUB_WORKFLOW}\\nTrigger: ${GITHUB_EVENT_NAME}\Commit: ${GITHUB_SHA}\\nResult: ${JOB_STATUS}\\nURL: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          JOB_STATUS: ${{ job.status }}