name: Caller workflow

on:
  workflow_dispatch:
  push:

jobs:
  caller_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Echo
        run: |
          echo "Caller workflow echo!"

  call-workflow-passing-data:
    needs: caller_workflow
    uses: vyos/community.vyos.net/.github/workflows/main.yml@main
    secrets: inherit
