name: Caller workflow

on:
  workflow_dispatch:
  push:

jobs:
  caller_workflow:
    runs-on: ubuntu-latest
    steps:


      - name: touch test.txt
        run: |
          echo BLABLA > ./test.txt

      - name: Run SSH test
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          connect_timeout: 10s
          first_ssh: |
            whoami
            echo LALALA_1
          scp: |
            './test.txt' => '~/'
          last_ssh: |
            cat ~/test.txt
            exit 1
            echo LALALA_2