name: Fail test workflow

on:
  push:
  workflow_dispatch:
    inputs:
      SKIP_SMOKETEST:
        description: 'Skip smoketest'
        required: true
        type: boolean
        default: false

jobs:
  job1:
    runs-on: ubuntu-latest
    concurrency:
      group: main
    steps:

      - run: |
          sleep 1000
        if:  ${{ !inputs.SKIP_SMOKETEST }} 