name: Workflow 2

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        id: step1
        run: |
          true

      - name: Step 2
        id: step2
        run: |
          false

      - name: Step 3
        id: step3
        run: |
          true

      - name: Capture failed step
        if: failure() 
        run: |
          echo '${{ toJson(jobs) }}' > github-context.json

      - name: Create Artifact
        if: failure() 
        uses: actions/upload-artifact@v2
        with:
          name: github-context.json
          path: github-context.json