name: Fail test workflow

on:
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Task 1
        id: task1
        run: |
          echo "Task 1"

      - name: Task 2
        id: task2
        run: |
          echo "Task 2"

      - name: Task 3
        id: task3
        run: |
          echo "Task 3"

      # - name: Send notification on fail
      #   id: notification
      #   if: always()
      #   # if: always() && steps.task2.conclusion == 'failure'
      #   run: |
      #     echo "$OUTPUT"
      #   env:
      #     OUTPUT: ${{ steps.task2.outputs }}

      - name: Get Workflow Run Link
        run: |
          echo "Repository: ${GITHUB_REPOSITORY}\nWorkflow: ${GITHUB_WORKFLOW}\nTrigger: ${GITHUB_EVENT_NAME}\Commit: ${GITHUB_SHA}\nResult: ${{ job.status }}\n$URL: {GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"