name: Fail test workflow

on:
  workflow_dispatch:
  push:

jobs:
  fail_test_workflow:
    runs-on: ubuntu-latest
    steps:

      - name: Task 1
        id: task1
        run: |
          echo "Task 1"

      - name: Task 2
        id: task2
        run: |
          echo "Task 2"
          exit 2

      - name: Task 3
        id: task3
        run: |
          echo "Task 3"

      - name: Send notification on fail
        id: notification
        if: always()
        # if: steps.task2.conclusion == 'failure'
        run: |
          echo "OUTPUT=$OUTPUT"
        env:
          OUTPUT: ${{ steps.task2 }}