name: Fail test workflow

on:
  workflow_dispatch:
    inputs:
      BUILD_BY:
        description: 'Builder identifier (if empty autobuild@vyos.net is used)'
        default: 'autobuild@vyos.net'
      BUILD_VERSION:
        description: 'Version number (if empty 1.5-rolling-DATE is used)'
        default: '1.5-rolling-DATE'

jobs:
  job1:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.inputs.BUILD_BY }}
          echo ${{ github.event.inputs.BUILD_VERSION }}

          if [ -z "${{ github.event.inputs.BUILD_BY }}" ]; then
            echo "BUILD_BY=1.5-rolling-$(date -u +%Y%m%d%H%M)" >> $GITHUB_ENV
          fi
          if [ -z "${{ github.event.inputs.BUILD_VERSION }}" ]; then
            echo "BUILD_VERSION=1.5-rolling-$(date -u +%Y%m%d%H%M)" >> $GITHUB_ENV
          fi

          echo ${{ env.BUILD_VERSION }}
          echo ${{ env.BUILD_VERSION }}

