name: Fail test workflow

on:
  workflow_dispatch:
    inputs:
      BUILD_BY:
        description: 'Builder identifier (e.g. jrandomhacker@example.net)'
        default: 'autobuild@vyos.net'
        required: true
      BUILD_VERSION:
        description: 'Version number (if empty 1.4-rolling-DATE is used)'

jobs:
  job1:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.inputs.BUILD_BY }}
