name: Caller workflow

on:
  workflow_dispatch:
  push:

jobs:
  caller_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Echo
        run: |
          echo "Caller workflow echo #1!"

      - name: Simple Echo
        run: |
          echo "Caller workflow echo #2!"
