name: Workflow 2

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        id: step1
        run: |
          true

      - name: Step 2
        id: step2
        run: |
          false

      - name: Step 3
        id: step3
        run: |
          true

      - run: |
          false

      - name: Step 5
        run: |
          false

      - id: step6
        run: |
          true

      - name: Capture failed step
        if: failure() 
        run: |
          echo '${{ toJson(steps) }}' | jq '.'

      # - name: Create Artifact
      #   if: failure() 
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: github.json
      #     path: github.json
      # - name: Create Artifact
      #   if: failure() 
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: job.json
      #     path: job.json
      # - name: Create Artifact
      #   if: failure() 
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: steps.json
      #     path: steps.json