name: Minisign test

on:
  push:

  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

jobs:
  minisign-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Set VyOS version
        id: set_vyos_version
        run: |
          echo "VYOS_VERSION=1.4-rolling-$(date -u +%Y%m%d%H%M)" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - run: |
          echo $VYOS_VERSION > vyos-$VYOS_VERSION-amd64.iso

      - name: Check ISO
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          VYOS_VERSION: ${{ env.VYOS_VERSION }}
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          connect_timeout: 10s
          first_ssh: |
            rm -rf ~/vyos-build || true
            git clone -b current --single-branch https://github.com/vyos/vyos-build
            mkdir -p ~/vyos-build/build/
          scp: |
            './vyos-$VYOS_VERSION-amd64.iso' => ~/vyos-build/build/live-image-amd64.hybrid.iso
          last_ssh: |
            docker run --rm --privileged -v ~/vyos-build:/vyos -w /vyos vyos/vyos-build:current sudo make testc