name: Fail test workflow

on:
  push:
  workflow_dispatch:
    inputs:
      SKIP_SMOKETEST:
        description: 'False to skip smoketest'
        required: true
        type: boolean
        default: false

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:

      - run: |
          echo SMOKETEST
        if:  ${{ !inputs.SKIP_SMOKETEST }} 