name: Caller workflow

on:
  workflow_dispatch:
  push:

jobs:
  caller_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Echo
        run: |
          echo "Caller workflow echo!"

  call-workflow-passing-data:
    uses: andriiandrieiev/github-actions-tests/.github/workflows/workflow.yml@main
