name: Caller workflow

on:
  workflow_dispatch:
  push:

jobs:
  # caller_workflow:
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: Simple Echo
  #       run: |
  #         git clone https://github.com/vyos/community.vyos.net.git .

  call-workflow-passing-data:
    # needs: caller_workflow
    uses: vyos/community.vyos.net/.github/workflows/main.yml@production
    secrets:
       NETLIFY_SITE_NAME: ${{ secrets.NETLIFY_SITE_NAME }}
       NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
       SOUPAULT_PROFILE: ${{ secrets.SOUPAULT_PROFILE }}
       GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
