name: Fail test workflow

on:
  push:
  workflow_dispatch:
    inputs:
      DO_SMOKETEST:
        description: 'False to skip smoketest'
        required: true
        type: boolean
        default: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:

      - run: |
          echo SMOKETEST
        if:  ${{ inputs.DO_SMOKETEST }} 