name: Fail test workflow

on:
  push:
  workflow_dispatch:
    inputs:
      SKIP_SMOKETEST_RAID1:
        description: 'Skip RAID1 smoketest'
        required: true
        type: boolean
        default: false

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:

      - run: |
          dateasdasdasdasd
      - run: |
          echo $SMOKETEST_RAID_COMMAND
        if:  failure() && !inputs.SKIP_SMOKETEST_RAID1 