name: Fail test workflow

on:
  push:
  workflow_dispatch:
    inputs:
      SKIP_SMOKETEST_RAID1:
        description: 'Skip RAID1 smoketest'
        required: true
        type: boolean
        default: false

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:

      - run: |
          if [ -z "${{ github.event.inputs.SKIP_SMOKETEST_RAID1 }}" ]; then
            echo "SMOKETEST_RAID_COMMAND='RAID TEST!'" >> $GITHUB_ENV
          else
            echo "SMOKETEST_RAID_COMMAND='DO" >> $GITHUB_ENV
          fi
      - run: |
          echo $SMOKETEST_RAID_COMMAND

  #### if:  ${{ !inputs.SKIP_SMOKETEST_RAID1 }} 