name: Fail test workflow

on:
  workflow_dispatch:
    inputs:
      BUILD_BY:
        description: 'Builder identifier (if empty autobuild@vyos.net is used)'
        default: 'autobuild@vyos.net'
      BUILD_VERSION:
        description: 'Version number (if empty 1.5-rolling-DATE is used)'
        default: '1.5-rolling-DATE'

jobs:
  job1:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.inputs.BUILD_BY }}
          echo ${{ github.event.inputs.BUILD_VERSION }}
