name: Workflow 2

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: |
          true

      - name: Step 2
        run: |
          false  # This step will intentionally fail
        continue-on-error: true

      - name: Step 3
        run: |
          true

      - name: Capture failed step
        if: failure() 
        run: |
          echo "${{ github.job }}"
