name: Fail test workflow

on:
  workflow_dispatch:
  push:

jobs:
  fail_test_workflow:
    runs-on: ubuntu-latest
    steps:

      - name: Task 1
        run: |
          echo "Task 1"

      - name: Task 2
        run: |
          echo "Task 2"
          exit 2

      - name: Task 3
        run: |
          echo "Task 3"

      - name: Send Slack notification on fail
        if: failure()
        run: |
          echo "FAILED"