name: Workflow 2

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "${{ secrets.multiline }}"
          echo "${{ secrets.multiline }}" > test.txt
          cat test.txt
