name: Caller workflow

on:
  workflow_dispatch:
  push:

jobs:
  caller_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Echo
        run: |
          echo "Caller workflow echo!"
          sleep 60

  call-workflow-passing-data:
    needs: caller_workflow
    uses: andriiandrieiev/github-actions-tests2/.github/workflows/workflow.yml@main
    secrets: inherit
